# Generated by Django 5.2.6 on 2025-09-26 08:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', 'start_time'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='occupieddate',
            options={'ordering': ['date'], 'verbose_name': 'Fecha Ocupada', 'verbose_name_plural': 'Fechas Ocupadas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='end_time_after_start_time',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_categor_73c0cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_name_a9c4c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_d_0b0e32_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_client__b30dce_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_status_8890b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_users_user_ty_c6da1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_users_created_3a6552_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_client',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('lighting', 'Iluminación'), ('staging', 'Escenario'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por Día'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='Hora de Finalización'),
        ),
        migrations.AlterField(
            model_name='event',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='events', to='authentication.equipment', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='all_day',
            field=models.BooleanField(default=True, verbose_name='Todo el Día'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='date',
            field=models.DateField(unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='reason',
            field=models.CharField(default='Fecha ocupada', max_length=200, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente')], default='client', max_length=10, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterModelTable(
            name='equipment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='occupieddate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.DeleteModel(
            name='EventHistory',
        ),
    ]
